#: import main Main
#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton

<CentrosCuadradosScreen>:

    BoxLayout:
        orientation: "vertical"

        BoxLayout:
            orientation: "horizontal"
            BoxLayout:
                id:drawing_box

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: None
            height: "40dp"
            Label:
                text: "Hola"
